[tool.poetry]
name = "pkiviewer"
version = "0.1.0"
description = "PKI Viewer"
authors = ["Simon Kennedy <sffjunkie+code@gmail.com>"]
license = "Apache-2.0"

packages = [
    { include = "pkiviewer", from = "src" },
    { include = "pkiviewer/py.typed", from = "src" },
]
include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.10"
cryptography = "^37.0.4"
rich = "^12.5.1"
tomli = "^2.0.1"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
tox = "^3.25.1"
typing-extensions = "^4.3.0"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]

[tool.poetry.scripts]
pkiviewer = 'pkiviewer.__main__:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.mypy.overrides]]
module = [
    'cryptography.*',
    'pkiviewer.asn1.json_encoder',
    'pkiviewer.model.csr'
]
ignore_errors = true
